<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllCategories()
    {
        $qb = $this->getEntityManager()->getRepository(Category::class)
            ->createQueryBuilder('cat')
            ->select('cat');
        return $qb->getQuery()->getArrayResult();
    }


}
