<?php

namespace AppBundle\Repository;

/**
 * FrequencyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrequencyTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
