<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Location;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllLocations()
    {
        $qb = $this->getEntityManager()->getRepository(Location::class)
            ->createQueryBuilder('loc')
            ->select('loc');
        return $qb->getQuery()->getArrayResult();
    }

    public function getLocationsByDistrictId($districtId){
        $qb = $this->getEntityManager()->getRepository(Location::class)
            ->createQueryBuilder('l')
            ->select('l')
            ->where('l.district=:district')
            ->setParameter('district',$districtId)
            ->getQuery();
        $result = $qb->getArrayResult();
        return $result;
    }
}
