<?php

namespace AppBundle\Repository;

use AppBundle\Entity\SubCategory;

/**
 * SubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSubCategoryListByCategoryId($categoryId){
        $qb = $this->getEntityManager()->getRepository(SubCategory::class)
            ->createQueryBuilder('sc')
            ->select('sc')
            ->where('sc.category=:category')
            ->setParameter('category',$categoryId)
            ->getQuery();
        $result = $qb->getArrayResult();
        return $result;
    }
}
