AppBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        icon:
            type: string
            length: 50
    oneToMany:
        subCategories:
            targetEntity: SubCategory
            mappedBy: category
    lifecycleCallbacks: {  }
