AppBundle\Entity\District:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DistrictRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
    oneToMany:
        locations:
            targetEntity: Location
            mappedBy: district
    lifecycleCallbacks: {  }
