AppBundle\Entity\Photo:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PhotoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            length: 255
    manyToOne:
        ad:
            targetEntity: Ad
            inversedBy: photos
            joinColumn:
                name: ad
                referencedColumnName: id
    lifecycleCallbacks: {  }
