#!/bin/bash

echo "inserting data...";
mysql --user=root --password=1234 rental_buddy << EOF
INSERT INTO category(name,description,icon) VALUES ('Vehicles','description','car');
INSERT INTO category(name,description,icon) VALUES ('Property','description','home');
INSERT INTO category(name,description,icon) VALUES ('Machinery','description','cogs');
INSERT INTO category(name,description,icon) VALUES ('Clothes/ Ornaments','description','female');
INSERT INTO category(name,description,icon) VALUES ('Electronics','description','laptop');
INSERT INTO category(name,description,icon) VALUES ('Entertainment','description','music');
INSERT INTO category(name,description,icon) VALUES ('Festival Items','description','shopping basket');
INSERT INTO category(name,description,icon) VALUES ('Sports','description','football ball');
INSERT INTO category(name,description,icon) VALUES ('Construction Items','description','building');
INSERT INTO category(name,description,icon) VALUES ('Travelling','description','plane');
INSERT INTO category(name,description,icon) VALUES ('Other','description','box');
INSERT INTO frequency_type(name) VALUES ('Hour(s)');
INSERT INTO frequency_type(name) VALUES ('Day(s)');
INSERT INTO frequency_type(name) VALUES ('Week(s)');
INSERT INTO frequency_type(name) VALUES ('Month(s)');
INSERT INTO frequency_type(name) VALUES ('Year(s)');
INSERT INTO sub_category(category,name) VALUES (1,'Car');
INSERT INTO sub_category(category,name) VALUES (1,'Van');
INSERT INTO sub_category(category,name) VALUES (1,'Motorbikes');
INSERT INTO sub_category(category,name) VALUES (1,'Push cycle');
INSERT INTO sub_category(category,name) VALUES (1,'Wedding car');
INSERT INTO sub_category(category,name) VALUES (1,'Lorry');
INSERT INTO sub_category(category,name) VALUES (1,'Heavy Machinery');
INSERT INTO sub_category(category,name) VALUES (1,'Boats And Water transport');
INSERT INTO sub_category(category,name) VALUES (2,'House');
INSERT INTO sub_category(category,name) VALUES (2,'Land');
INSERT INTO sub_category(category,name) VALUES (2,'Rooms & Annexes');
INSERT INTO sub_category(category,name) VALUES (2,'Apartments');
INSERT INTO sub_category(category,name) VALUES (2,'Commercial property');
INSERT INTO sub_category(category,name) VALUES (3,'Power tools');
INSERT INTO sub_category(category,name) VALUES (3,'Portable machines');
INSERT INTO sub_category(category,name) VALUES (3,'Equipments');
INSERT INTO sub_category(category,name) VALUES (4,'Blazers & Coats');
INSERT INTO sub_category(category,name) VALUES (4,'Bridal dress');
INSERT INTO sub_category(category,name) VALUES (4,'Groom wear');
INSERT INTO sub_category(category,name) VALUES (4,'Jewellery');
INSERT INTO sub_category(category,name) VALUES (5,'Sound systems');
INSERT INTO sub_category(category,name) VALUES (5,'Camera');
INSERT INTO sub_category(category,name) VALUES (5,'Laptops & Projectors');
INSERT INTO sub_category(category,name) VALUES (5,'Lighting equipments');
INSERT INTO sub_category(category,name) VALUES (6,'Musical Instruments');
INSERT INTO sub_category(category,name) VALUES (6,'DJ');
INSERT INTO sub_category(category,name) VALUES (6,'Recording studios');
INSERT INTO sub_category(category,name) VALUES (7,'Tents / Huts');
INSERT INTO sub_category(category,name) VALUES (7,'Chairs');
INSERT INTO sub_category(category,name) VALUES (7,'Buffet Set');
INSERT INTO sub_category(category,name) VALUES (7,'Water Sink and Pumps');
INSERT INTO sub_category(category,name) VALUES (7,'Pirith Mandappa');
INSERT INTO sub_category(category,name) VALUES (8,'Sport equipments');
INSERT INTO sub_category(category,name) VALUES (8,'Indoor/Outdoor stadiums');
INSERT INTO sub_category(category,name) VALUES (9,'Construction Equipments');
INSERT INTO sub_category(category,name) VALUES (9,'Construction Machinery');
INSERT INTO sub_category(category,name) VALUES (10,'Camping sites');
INSERT INTO sub_category(category,name) VALUES (10,'Bags');
INSERT INTO sub_category(category,name) VALUES (10,'Travelling Equipments');
INSERT INTO sub_category(category,name) VALUES (11,'Books');
INSERT INTO district(name) VALUES ('Ampara');
INSERT INTO district(name) VALUES ('Anuradhapura');
INSERT INTO district(name) VALUES ('Badulla');
INSERT INTO district(name) VALUES ('Batticaloa');
INSERT INTO district(name) VALUES ('Colombo');
INSERT INTO district(name) VALUES ('Galle');
INSERT INTO district(name) VALUES ('Gampaha');
INSERT INTO district(name) VALUES ('Hambanthota');
INSERT INTO district(name) VALUES ('Jaffna');
INSERT INTO district(name) VALUES ('Kaluthara');
INSERT INTO district(name) VALUES ('Kandy');
INSERT INTO district(name) VALUES ('Kegalle');
INSERT INTO district(name) VALUES ('Kilinochchi');
INSERT INTO district(name) VALUES ('Kurunegala');
INSERT INTO district(name) VALUES ('Mannar');
INSERT INTO district(name) VALUES ('Mathale');
INSERT INTO district(name) VALUES ('Matara');
INSERT INTO district(name) VALUES ('Monaragala');
INSERT INTO district(name) VALUES ('Mullaitivu');
INSERT INTO district(name) VALUES ('Nuwara eliya');
INSERT INTO district(name) VALUES ('Polonnaruwa');
INSERT INTO district(name) VALUES ('Puttalam');
INSERT INTO district(name) VALUES ('Rathnapura');
INSERT INTO district(name) VALUES ('Trincomalee');
INSERT INTO district(name) VALUES ('Vavuniya');
INSERT INTO location(district,name) VALUES (1,'Akkarepattu');
INSERT INTO location(district,name) VALUES (1,'Ampara');
INSERT INTO location(district,name) VALUES (1,'Kalmunai');
INSERT INTO location(district,name) VALUES (1,'Sainthamaruthu');
INSERT INTO location(district,name) VALUES (2,'Anuradapura');
INSERT INTO location(district,name) VALUES (2,'Eppawala');
INSERT INTO location(district,name) VALUES (2,'Galenbindunuwewa');
INSERT INTO location(district,name) VALUES (2,'Galnewa');
INSERT INTO location(district,name) VALUES (2,'Habarana');
INSERT INTO location(district,name) VALUES (2,'Kekirawa');
INSERT INTO location(district,name) VALUES (2,'Medawachchiya');
INSERT INTO location(district,name) VALUES (2,'Mihinthale');
INSERT INTO location(district,name) VALUES (2,'Nochchiyagama');
INSERT INTO location(district,name) VALUES (2,'Tambuththegama');
INSERT INTO location(district,name) VALUES (2,'Thalawa');
INSERT INTO location(district,name) VALUES (3,'Badulla');
INSERT INTO location(district,name) VALUES (3,'Bandarawela');
INSERT INTO location(district,name) VALUES (3,'Diyathalawa');
INSERT INTO location(district,name) VALUES (3,'Ella');
INSERT INTO location(district,name) VALUES (3,'Hali Ela');
INSERT INTO location(district,name) VALUES (3,'Haputhale');
INSERT INTO location(district,name) VALUES (3,'Mahiyanganaya');
INSERT INTO location(district,name) VALUES (3,'Passara');
INSERT INTO location(district,name) VALUES (3,'Welimada');
INSERT INTO location(district,name) VALUES (4,'Batticaloa');
INSERT INTO location(district,name) VALUES (5,'Angoda');
INSERT INTO location(district,name) VALUES (5,'Athuhrugiriya');
INSERT INTO location(district,name) VALUES (5,'Avissawella');
INSERT INTO location(district,name) VALUES (5,'Battaramulla');
INSERT INTO location(district,name) VALUES (5,'Boralesgamuwa');
INSERT INTO location(district,name) VALUES (5,'Colombo 1');
INSERT INTO location(district,name) VALUES (5,'Colombo 2');
INSERT INTO location(district,name) VALUES (5,'Colombo 3');
INSERT INTO location(district,name) VALUES (5,'Colombo 4');
INSERT INTO location(district,name) VALUES (5,'Colombo 5');
INSERT INTO location(district,name) VALUES (5,'Colombo 6');
INSERT INTO location(district,name) VALUES (5,'Colombo 7');
INSERT INTO location(district,name) VALUES (5,'Colombo 8');
INSERT INTO location(district,name) VALUES (5,'Colombo 9');
INSERT INTO location(district,name) VALUES (5,'Colombo 10');
INSERT INTO location(district,name) VALUES (5,'Colombo 11');
INSERT INTO location(district,name) VALUES (5,'Colombo 12');
INSERT INTO location(district,name) VALUES (5,'Colombo 13');
INSERT INTO location(district,name) VALUES (5,'Colombo 14');
INSERT INTO location(district,name) VALUES (5,'Colombo 15');
INSERT INTO location(district,name) VALUES (5,'Dehiwala');
INSERT INTO location(district,name) VALUES (5,'Hanwella');
INSERT INTO location(district,name) VALUES (5,'Homagama');
INSERT INTO location(district,name) VALUES (5,'Kaduwela');
INSERT INTO location(district,name) VALUES (5,'Kesbewa');
INSERT INTO location(district,name) VALUES (5,'Kohuwala');
INSERT INTO location(district,name) VALUES (5,'Kolonnawa');
INSERT INTO location(district,name) VALUES (5,'Kottawa');
INSERT INTO location(district,name) VALUES (5,'Kotte');
INSERT INTO location(district,name) VALUES (5,'Maharagama');
INSERT INTO location(district,name) VALUES (5,'Malabe');
INSERT INTO location(district,name) VALUES (5,'Moratuwa');
INSERT INTO location(district,name) VALUES (5,'Mount Lavinia');
INSERT INTO location(district,name) VALUES (5,'Nawala');
INSERT INTO location(district,name) VALUES (5,'Nugegoda');
INSERT INTO location(district,name) VALUES (5,'Padukka');
INSERT INTO location(district,name) VALUES (5,'Pannipitiya');
INSERT INTO location(district,name) VALUES (5,'Piliyandala');
INSERT INTO location(district,name) VALUES (5,'Rajagiriya');
INSERT INTO location(district,name) VALUES (5,'Ratmalana');
INSERT INTO location(district,name) VALUES (5,'Talawatugoda');
INSERT INTO location(district,name) VALUES (5,'Wellampitiya');
INSERT INTO location(district,name) VALUES (6,'Ahangama');
INSERT INTO location(district,name) VALUES (6,'Ambalangoda');
INSERT INTO location(district,name) VALUES (6,'Baddegama');
INSERT INTO location(district,name) VALUES (6,'Batapola');
INSERT INTO location(district,name) VALUES (6,'Bentota');
INSERT INTO location(district,name) VALUES (6,'Elpitiya');
INSERT INTO location(district,name) VALUES (6,'Galle');
INSERT INTO location(district,name) VALUES (6,'Hikkaduwa');
INSERT INTO location(district,name) VALUES (6,'Karapitiya');
INSERT INTO location(district,name) VALUES (7,'Delgoda');
INSERT INTO location(district,name) VALUES (7,'Divulapitiya');
INSERT INTO location(district,name) VALUES (7,'Gampaha');
INSERT INTO location(district,name) VALUES (7,'Ganemulla');
INSERT INTO location(district,name) VALUES (7,'Ja-Ela');
INSERT INTO location(district,name) VALUES (7,'Kadawatha');
INSERT INTO location(district,name) VALUES (7,'Kandana');
INSERT INTO location(district,name) VALUES (7,'Katunayake');
INSERT INTO location(district,name) VALUES (7,'Kelaniya');
INSERT INTO location(district,name) VALUES (7,'Kiribathgoda');
INSERT INTO location(district,name) VALUES (7,'Minuwangoda');
INSERT INTO location(district,name) VALUES (7,'Mirigama');
INSERT INTO location(district,name) VALUES (7,'Negombo');
INSERT INTO location(district,name) VALUES (7,'Nittambuwa');
INSERT INTO location(district,name) VALUES (7,'Ragama');
INSERT INTO location(district,name) VALUES (7,'Veyangoda');
INSERT INTO location(district,name) VALUES (7,'Wattala');
INSERT INTO location(district,name) VALUES (8,'Thangalla');
INSERT INTO location(district,name) VALUES (8,'Beliaththa');
INSERT INTO location(district,name) VALUES (8,'Ambalantota');
INSERT INTO location(district,name) VALUES (8,'Thissamaharama');
INSERT INTO location(district,name) VALUES (8,'Hambanthota');
INSERT INTO location(district,name) VALUES (9,'Chavakachcheri');
INSERT INTO location(district,name) VALUES (9,'Jaffna');
INSERT INTO location(district,name) VALUES (9,'Nallur');
INSERT INTO location(district,name) VALUES (10,'Aluthgama');
INSERT INTO location(district,name) VALUES (10,'Bandaragama');
INSERT INTO location(district,name) VALUES (10,'Beruwala');
INSERT INTO location(district,name) VALUES (10,'Horana');
INSERT INTO location(district,name) VALUES (10,'Ingiriya');
INSERT INTO location(district,name) VALUES (10,'Kaluthara');
INSERT INTO location(district,name) VALUES (10,'Mathugama');
INSERT INTO location(district,name) VALUES (10,'Panadura');
INSERT INTO location(district,name) VALUES (10,'Wadduwa');
INSERT INTO location(district,name) VALUES (11,'Akurana');
INSERT INTO location(district,name) VALUES (11,'Ampitiya');
INSERT INTO location(district,name) VALUES (11,'Digana');
INSERT INTO location(district,name) VALUES (11,'Galagedara');
INSERT INTO location(district,name) VALUES (11,'Gampola');
INSERT INTO location(district,name) VALUES (11,'Gelioya');
INSERT INTO location(district,name) VALUES (11,'Kadugannawa');
INSERT INTO location(district,name) VALUES (11,'Kandy');
INSERT INTO location(district,name) VALUES (11,'Katugasthota');
INSERT INTO location(district,name) VALUES (11,'Kundasale');
INSERT INTO location(district,name) VALUES (11,'Madawala Bazaar');
INSERT INTO location(district,name) VALUES (11,'Nawalapitiya');
INSERT INTO location(district,name) VALUES (11,'Peradeniya');
INSERT INTO location(district,name) VALUES (11,'Pilimathalawa');
INSERT INTO location(district,name) VALUES (11,'Wattegama');
INSERT INTO location(district,name) VALUES (12,'Dehiowita');
INSERT INTO location(district,name) VALUES (12,'Deraniyagala');
INSERT INTO location(district,name) VALUES (12,'Galigamuwa');
INSERT INTO location(district,name) VALUES (12,'Kegalle');
INSERT INTO location(district,name) VALUES (12,'Kithulgala');
INSERT INTO location(district,name) VALUES (12,'Mawanella');
INSERT INTO location(district,name) VALUES (12,'Rambukkana');
INSERT INTO location(district,name) VALUES (12,'Warakapola');
INSERT INTO location(district,name) VALUES (12,'Yayiyanthota');
INSERT INTO location(district,name) VALUES (13,'Kilinochchi');
INSERT INTO location(district,name) VALUES (14,'Alawwa');
INSERT INTO location(district,name) VALUES (14,'Bingiriya');
INSERT INTO location(district,name) VALUES (14,'Galgamuwa');
INSERT INTO location(district,name) VALUES (14,'Giriulla');
INSERT INTO location(district,name) VALUES (14,'Hettipola');
INSERT INTO location(district,name) VALUES (14,'Ibbagamuwa');
INSERT INTO location(district,name) VALUES (14,'Kuliyapitiya');
INSERT INTO location(district,name) VALUES (14,'Kurunegala');
INSERT INTO location(district,name) VALUES (14,'Mawathagama');
INSERT INTO location(district,name) VALUES (14,'Narammala');
INSERT INTO location(district,name) VALUES (14,'Nikaweratiya');
INSERT INTO location(district,name) VALUES (14,'Pannala');
INSERT INTO location(district,name) VALUES (14,'Polgahawela');
INSERT INTO location(district,name) VALUES (14,'Wariyapola');
INSERT INTO location(district,name) VALUES (15,'Mannar');
INSERT INTO location(district,name) VALUES (16,'Dambulla');
INSERT INTO location(district,name) VALUES (16,'Galewela');
INSERT INTO location(district,name) VALUES (16,'Matale');
INSERT INTO location(district,name) VALUES (16,'Palapathwela');
INSERT INTO location(district,name) VALUES (16,'Rattota');
INSERT INTO location(district,name) VALUES (16,'Sigiriya');
INSERT INTO location(district,name) VALUES (16,'Ukuwela');
INSERT INTO location(district,name) VALUES (16,'Yatawatta');
INSERT INTO location(district,name) VALUES (17,'Akuressa');
INSERT INTO location(district,name) VALUES (17,'Deniyaya');
INSERT INTO location(district,name) VALUES (17,'Dikwella');
INSERT INTO location(district,name) VALUES (17,'Hakmana');
INSERT INTO location(district,name) VALUES (17,'Kamburugamuwa');
INSERT INTO location(district,name) VALUES (17,'Kamburupitiya');
INSERT INTO location(district,name) VALUES (17,'Kekanadurra');
INSERT INTO location(district,name) VALUES (17,'Matara');
INSERT INTO location(district,name) VALUES (17,'Weligama');
INSERT INTO location(district,name) VALUES (18,'Bibile');
INSERT INTO location(district,name) VALUES (18,'Buttala');
INSERT INTO location(district,name) VALUES (18,'Kataragama');
INSERT INTO location(district,name) VALUES (18,'Monaragala');
INSERT INTO location(district,name) VALUES (18,'Wellawaya');
INSERT INTO location(district,name) VALUES (19,'Mullativu');
INSERT INTO location(district,name) VALUES (20,'Ginigathena');
INSERT INTO location(district,name) VALUES (20,'Hatton');
INSERT INTO location(district,name) VALUES (20,'Madulla');
INSERT INTO location(district,name) VALUES (20,'Nuwara eliya');
INSERT INTO location(district,name) VALUES (21,'Hingurakgoda');
INSERT INTO location(district,name) VALUES (21,'Kaduruwela');
INSERT INTO location(district,name) VALUES (21,'Medirigiriya');
INSERT INTO location(district,name) VALUES (21,'Polonnaruwa');
INSERT INTO location(district,name) VALUES (22,'Chilaw');
INSERT INTO location(district,name) VALUES (22,'Dankotuwa');
INSERT INTO location(district,name) VALUES (22,'Marawila');
INSERT INTO location(district,name) VALUES (22,'Nattandiya');
INSERT INTO location(district,name) VALUES (22,'Puttalam');
INSERT INTO location(district,name) VALUES (22,'Wennappuwa');
INSERT INTO location(district,name) VALUES (23,'Balangoda');
INSERT INTO location(district,name) VALUES (23,'Eheliyagoda');
INSERT INTO location(district,name) VALUES (23,'Embilipitiya');
INSERT INTO location(district,name) VALUES (23,'Kuruwita');
INSERT INTO location(district,name) VALUES (23,'Pelmadulla');
INSERT INTO location(district,name) VALUES (23,'Rathnapura');
INSERT INTO location(district,name) VALUES (24,'Kinniya');
INSERT INTO location(district,name) VALUES (24,'Trincomalee');
INSERT INTO location(district,name) VALUES (25,'Vavuniya');
EOF

echo "SUCCESS";